'use client';

import React from 'react';
import Icon from '@/components/ui/AppIcon';

interface AIRoutingIndicatorProps {
  observationLength: number;
  topic: string;
  isCacheHit: boolean;
  // Actual backend state — populated after API responds
  providerUsed?: string | null;
  responseTimeMs?: number | null;
  isSensitiveFromBackend?: boolean | null;
}

const SENSITIVE_TOPICS = [
  'Emotional Resilience and Mental Well-being',
  'Personal Safety, Consent, and Boundaries',
];

const PROVIDER_LABELS: Record<string, { label: string; badge: string }> = {
  Gemini: { label: 'Gemini (Primary)', badge: 'badge-positive' },
  Groq: { label: 'Groq Llama 3.3 (Fallback 1)', badge: 'badge-info' },
  Cohere: { label: 'Cohere Command R+ (Fallback 2)', badge: 'badge-warning' },
  OpenRouter: { label: 'OpenRouter Llama (Fallback 3)', badge: 'badge-warning' },
  HuggingFace: { label: 'HuggingFace Mistral (Fallback 4)', badge: 'badge-warning' },
};

export default function AIRoutingIndicator({
  observationLength,
  topic,
  isCacheHit,
  providerUsed,
  responseTimeMs,
  isSensitiveFromBackend,
}: AIRoutingIndicatorProps) {
  if (!topic) return null;

  // If we have actual backend data, show the real result
  if (providerUsed) {
    const isSensitive = isSensitiveFromBackend ?? SENSITIVE_TOPICS.includes(topic);
    const providerInfo = PROVIDER_LABELS[providerUsed] ?? { label: providerUsed, badge: 'badge-info' };
    const isGeminiPrimary = providerUsed === 'Gemini';
    const isFallback = !isGeminiPrimary;

    return (
      <div className={`rounded-xl border p-4 ${isFallback ? 'bg-warning/10 border-warning/20' : 'bg-positive/10 border-positive/20'}`}>
        <div className="flex items-start gap-3">
          <div className={`w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 ${isFallback ? 'bg-warning/15' : 'bg-positive/15'}`}>
            <Icon
              name={isFallback ? 'ArrowPathIcon' : 'CheckCircleIcon'}
              size={17}
              className={isFallback ? 'text-warning' : 'text-positive'}
            />
          </div>
          <div className="flex-1">
            <div className="flex items-center gap-2 flex-wrap">
              <p className="text-sm font-700 text-foreground">
                {isFallback ? 'Fallback Provider Used' : 'Analysis Complete'}
              </p>
              <span className={`status-badge text-xs ${providerInfo.badge}`}>
                {providerInfo.label}
              </span>
              {responseTimeMs != null && (
                <span className="status-badge badge-info text-xs">
                  <Icon name="ClockIcon" size={11} /> {(responseTimeMs / 1000).toFixed(1)}s
                </span>
              )}
            </div>
            <p className="text-xs text-muted-foreground mt-1 leading-relaxed">
              {isFallback
                ? `Gemini was unavailable — analysis was routed to ${providerInfo.label} via the waterfall failover engine.${responseTimeMs != null ? ` Total response time: ${(responseTimeMs / 1000).toFixed(1)}s.` : ''}`
                : `Analysis generated by Gemini (primary provider).${responseTimeMs != null ? ` Response time: ${(responseTimeMs / 1000).toFixed(1)}s.` : ''}`}
            </p>
            {isSensitive && (
              <div className="flex items-center gap-1.5 mt-2 px-2 py-1 rounded-lg bg-warning/10 border border-warning/20 w-fit">
                <Icon name="ShieldCheckIcon" size={12} className="text-warning" />
                <p className="text-xs text-warning font-600">Sensitive pillar — enhanced persona was active</p>
              </div>
            )}
          </div>
        </div>
      </div>
    );
  }

  // Pre-submission: show routing plan based on topic + observation length
  const isSensitive = SENSITIVE_TOPICS.includes(topic);
  const isComplex = observationLength > 300 || isSensitive;

  const model = isComplex ? 'Gemini Pro (Free Tier)' : 'Gemini Flash (Free Tier)';
  const modelColor = isComplex ? 'text-info' : 'text-positive';
  const modelBg = isComplex ? 'bg-info/10 border-info/20' : 'bg-positive/10 border-positive/20';

  return (
    <div className={`rounded-xl border p-4 ${isCacheHit ? 'bg-accent/10 border-accent/20' : modelBg}`}>
      <div className="flex items-start gap-3">
        <div className={`w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 ${
          isCacheHit ? 'bg-accent/20' : isComplex ? 'bg-info/15' : 'bg-positive/15'
        }`}>
          <Icon
            name={isCacheHit ? 'BoltIcon' : 'CpuChipIcon'}
            size={17}
            className={isCacheHit ? 'text-accent-foreground' : modelColor}
          />
        </div>
        <div className="flex-1">
          <div className="flex items-center gap-2 flex-wrap">
            <p className="text-sm font-700 text-foreground">
              {isCacheHit ? 'Cache Match Detected' : 'AI Routing Plan'}
            </p>
            {isCacheHit ? (
              <span className="status-badge badge-warning text-xs">
                <Icon name="BoltIcon" size={11} /> Smart Cache
              </span>
            ) : (
              <span className={`status-badge text-xs ${isComplex ? 'badge-info' : 'badge-positive'}`}>
                {model}
              </span>
            )}
          </div>
          <p className="text-xs text-muted-foreground mt-1 leading-relaxed">
            {isCacheHit
              ? "A similar session exists in this student's history. The AI will adapt the previous analysis rather than generating from scratch — saving time and resources."
              : isComplex
              ? `This session involves a sensitive pillar ("${topic}") or detailed observations. Routing to Gemini Pro for deeper, more nuanced analysis across all five observation areas.`
              : `Standard session detected. Routing to Gemini Flash for fast, efficient analysis of all five observation areas. Actual response time will be shown after submission.`}
          </p>
          {isSensitive && !isCacheHit && (
            <div className="flex items-center gap-1.5 mt-2 px-2 py-1 rounded-lg bg-warning/10 border border-warning/20 w-fit">
              <Icon name="ShieldCheckIcon" size={12} className="text-warning" />
              <p className="text-xs text-warning font-600">Sensitive pillar — enhanced persona active</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}